---
title: "Data Manipulation"
author: "Kylie Wheelock Riley"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Import datasets
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)

```

## Selecting columns/ vars to use in analysis

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

##Pulls everthing that starts with pups
select(litters_data, litter_number, gd0_weight, starts_with("pups"))

##rearranges columns so it is littler number, group, then everthing else
select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())

##if you want the data from column gd0_eright through pups_born_alive
select(litters_data, litter_number, gd0_weight:pups_born_alive)

##renaming group to GROUP, can use if var names are too descriptive/long
select(litters_data, GROUP = group, litter_number)

##this just renames without selecting columns
rename(litters_data, GROUP = group)
```


## Filtering!

```{r}
##when this is true keep that row, only keeps the Con 7 group
filter(litters_data, group == "Con7")

filter(litters_data, group == "Mod8")

##Showing only pups with a gestation of 20 days
filter(litters_data, gd_of_birth == 20)

##gestational daya less than 20
filter(litters_data, gd_of_birth < 20)

##looking for pups born alive < 6 and those in group Con7
filter(litters_data, pups_born_alive < 6, group == "Con7")

##greater than or = to 4 pups or greater than = to 6
filter(litters_data, pups_born_alive >= 4, pups_born_alive <= 6)

##What todo about missing values 
##DONT DO THIS
###filter(litters_data, !is.na(gd0_weight))

##DO THIS INSTEAD
drop_na(litters_data, gd0_weight)
```

## Mutate

```{r}
##mutate changes variables
##creates a variable of the difference in weight between gd0 and gd18, also changes column name to lowercase
mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))


```


## Arrange

```{r}
##usually used for viewing data/ double checking
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

##arranging on 2 different things
arrange(litters_data, pups_born_alive, gd0_weight)
```

## pipe ...

Create a collection of commands...

```{r}
#hotkey = ctrl + shift + m
litters_data = 
  read_csv("./data/FAS_litters.csv") %>%  
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight, 
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)

litters_data = 
  read_csv("./data/FAS_litters.csv") %>%  
  janitor::clean_names(dat = .) %>% 
  select(.data = .,-pups_survive)
```

