---
title: "Data_Tidying"
author: "Kylie Wheelock Riley"
date: "9/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
options(tibble.print_min = 5)
```

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    pulse_data,
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
    ) 
  
##Change baseline (bl) var to 00m to match other vars
mutate(
  visit = recode(visit, "bl" = "00m")
)

##visit is stored as a character, would likely need to make changes to it

```


```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% separate(col = group, into = c("dose", "day_of_tx"), 3)
```

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
```


